In [1]:
import numpy as np

Кластеризация методом k-средних.

In [26]:
data = np.array([np.random.uniform(-100, 110, 150), np.random.uniform(-90, 150, 150)]).T

k = 3
ridx = np.random.choice(range(len(data)), k, replace=False)
centroids = data[ridx, :]
dists = np.zeros((data.shape[0], k))
print(centroids)
for i in range(50):
    for kl in range(k):
        dists[:, kl] = np.sum((data-centroids[kl, :])**2, axis=1)

    groupidx = np.argmin(dists, axis=1)
    for ki in range(k):
        centroids[ki, :] = [np.mean(data[groupidx==ki, 0]), np.mean(data[groupidx==ki, 1])]

    print(centroids)

[[-54.80815481 -61.11297671]
 [ 51.15107067  43.46311799]
 [100.89798836  54.4798618 ]]
[[-43.56708234 -46.43462954]
 [ 13.71166916  46.46075908]
 [ 90.21500187  72.67707184]]
[[-20.15923491 -53.38704557]
 [ -8.17069603  63.45185179]
 [ 82.43538967  70.60602271]]
[[ -8.54559813 -54.98940283]
 [-23.6418298   75.95975775]
 [ 79.66811192  66.84059265]]
[[ -2.68545092 -56.47097227]
 [-31.81331075  76.10866842]
 [ 73.07197306  69.73898179]]
[[ -2.68545092 -56.47097227]
 [-36.69121433  75.98434276]
 [ 68.54150479  70.48474494]]
[[ -2.68545092 -56.47097227]
 [-41.72732415  76.90224772]
 [ 64.09850144  70.10492925]]
[[ -2.68545092 -56.47097227]
 [-43.00044707  77.00607339]
 [ 62.98457244  70.15677266]]
[[ -2.68545092 -56.47097227]
 [-43.00044707  77.00607339]
 [ 62.98457244  70.15677266]]
[[ -2.68545092 -56.47097227]
 [-43.00044707  77.00607339]
 [ 62.98457244  70.15677266]]
[[ -2.68545092 -56.47097227]
 [-43.00044707  77.00607339]
 [ 62.98457244  70.15677266]]
[[ -2.68545092 -56.47097227]
 [-