In [14]:
import numpy as np
import sympy as sym

In [ ]:
A = np.random.randn(4, 4)
B = np.random.randn(4, 4)
A @ (np.linalg.inv(A) @ B) - B

array([[ 8.32667268e-17,  0.00000000e+00, -5.55111512e-17,
         0.00000000e+00],
       [-1.11022302e-16, -1.11022302e-16, -1.38777878e-16,
        -1.66533454e-16],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
        -1.11022302e-16],
       [ 2.22044605e-16, -7.77156117e-16,  0.00000000e+00,
         1.11022302e-16]])

In [ ]:
# Нахождение обратной матрицы через rref 

A = np.random.randn(2, 4) 
A[:,2:4] = np.eye(2, 2)
A_inv = np.linalg.inv(A[:, :2])
sym_a = sym.Matrix(A).rref()
sym_a[0], A_inv

(Matrix([
 [1, 0, 0.0934026418827582,  0.557899742182836],
 [0, 1, -0.814330307930174, 0.0280808679814866]]),
 array([[ 0.09340264,  0.55789974],
        [-0.81433031,  0.02808087]]))

In [47]:
import scipy.linalg as sl

A = np.random.randn(4, 4)
_, L, U = sl.lu(A)
_, L, U, A @ np.linalg.inv(L) 

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.23167349,  1.        ,  0.        ,  0.        ],
        [-0.45419189,  0.05219345,  1.        ,  0.        ],
        [ 0.28843432, -0.78109191,  0.12194879,  1.        ]]),
 array([[-3.21304783,  0.18320913, -0.17012691, -0.46602199],
        [ 0.        , -1.59792286,  0.89613895, -0.13449805],
        [ 0.        ,  0.        ,  1.68599998,  1.87769438],
        [ 0.        ,  0.        ,  0.        , -2.02180197]]),
 array([[ 0.14305944, -1.79112274,  0.88629312, -0.24246299],
        [-0.52261411, -0.10555675, -0.32121893, -1.82218081],
        [ 1.2460922 ,  1.37866561,  1.55610424,  2.08233787],
        [-3.08957337, -0.17488356, -0.11329609, -0.46602199]]))